#!/bin/sh

# suspend to RAM

brightness=`cat /sys/class/backlight/*/brightness | head -1`

chvt 1
/etc/init.d/bluetooth stop || true
rfkill block all
#vbstate=/var/lib/vbetool.state
#vbetool vbestate save > $vbstate
sync

sleep 1
s2ram

chvt 7

echo $brightness > `echo /sys/class/backlight/*/brightness | head -1`

su - garabik -c "DISPLAY=:0.0 exec /usr/bin/xrandr --auto"


